language: python
services:
  - postgresql
  - redis-server
python:
  - "2.7"
install: 
  - "pip install -r requirements/test.txt"
script: 
  - ./{{cookiecutter.app_name}}/manage.py test --with-progressive --logging-clear-handlers
after_success:
  - coveralls

deploy:
  provider: heroku
  app:
    master: {{cookiecutter.app_name}}-dev
    qa: {{cookiecutter.app_name}}-qa
    prod: {{cookiecutter.app_name}}-prod
  on: 
    repo: {{cookiecutter.github_repository_name}}
  run:
    - "./{{cookiecutter.app_name}}/mange.py migrate"

# This reportedly works around an issue downloading packages from pypi on
# travis. Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
    fast_finish: true