version: '2'

services:
  redis:
    image: redis:3.2
  postgres:
    image: postgres:9.6
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    command: >
      bash -c "./viral/manage.py migrate &&
               ./viral/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
