sudo: required
language: python
cache: pip

python:
  - "2.7"
  - "3.6"
services:
  - docker
install:
  - pip install cookiecutter
  - cookiecutter . --no-input
  - cd piedpiper-web
before_script:
  - docker-compose up
script:
  - docker run --rm web ./piedpiper/manage.py test

notifications:
  email: false
