title: cookiecutter-django-rest
description: a factory for building bleeding edge, best practiced, scalable, rest apis. 
google_analytics: UA-42266786-6
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
