title: Cookiecutter-django-rest
description: For scaffolding REST apis for rapidly developing mobile products. 
google_analytics: UA-42266786-6
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
