version: '2'
services:
  redis:
    restart: always
    image: redis:3.2
    ports:
      - "6379:6379"
  postgres:
    image: postgres:9.6
  web:
    env_file: ./.env
    build: ../
    volumes:
      - ../:/code
    ports:
      - 8000
    depends_on:
      - postgres
  worker:
    env_file: ./.env
    restart: always
    build: ../
    command: ./{{cookiecutter.app_name}}/manage.py rqworker default
    volumes:
      - ../:/code
    ports:
      - "8001:8000"
    links:
      - redis
      - postgres
