version: '2'
services:
  redis:
   image: redis:3.0
  postgres:
   image: postgres:9.6
  web:
   build: ../
   command: newrelic-admin run-program gunicorn --pythonpath="$PWD/{{ cookiecutter.app_name }}" wsgi:application
   volumes:
     - ../:/code
   ports:
     - "8000:8000"
   depends_on:
     - postgres
     - redis
  worker:
    build: ../
    command: ./{{cookiecutter.app_name}}/manage.py rqworker default
    volumes:
      - ../:/code
    depends_on:
      - postgres
      - redis
