site_name: {{cookiecutter.project_name}}
site_description: {{cookiecutter.description}}
repo_url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repository_name}}
site_dir: site
copyright: Copyright &copy; 2021, <a href="https://github.com/11th-Hour-Data-Science">11th-Hour-Data-Science</a>.
dev_addr: 0.0.0.0:8001

theme:
  name: material
nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
